{% set name = "imexam" %}
{% set version = "0.8.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "ca179f34b3f89afc6e9c27d26cbe9f75c5f061f71fb6ebe2e4e1eae6e87ba908" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
  run:
    - python
    - astropy
    - matplotlib
    - ginga
    - ipython
    - scipy
    - photutils

test:
  imports:
    - imexam

about:
  home: http://imexam.readthedocs.io
  license: BSD 3-clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A package to help perform command-line image examination and plotting
  description: |
    imexam is an affiliated package of AstroPy. It was designed to be a
    lightweight library which enables users to explore data from a command
    line interface, through a Jupyter notebook or through a Jupyter console.
    It can be used with multiple viewers, such as DS9 or Ginga, or without a
    viewer as a simple library to make plots and grab quick photometry
    information. It has been designed so that other viewers may be easily
    attached in the future.
  doc_url: http://imexam.readthedocs.io
  dev_url: https://github.com/spacetelescope/imexam

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - sosey
