{% set name = "imexam" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5b73604b693c003d10e41a77016e3fd16ec035519aa74de8508e6614aa72652

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - setuptools_scm
    - cython
  run:
    - python
    - numpy >=1.14
    - astropy >=3
    - matplotlib-base
    - ginga
    - scipy >=0.18
    - photutils

test:
  imports:
    - imexam

about:
  home: http://imexam.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A package to help perform command-line image examination and plotting
  description: |
    imexam is an affiliated package of AstroPy. It was designed to be a
    lightweight library which enables users to explore data from a command
    line interface, through a Jupyter notebook or through a Jupyter console.
    It can be used with multiple viewers, such as DS9 or Ginga, or without a
    viewer as a simple library to make plots and grab quick photometry
    information. It has been designed so that other viewers may be easily
    attached in the future.
  doc_url: http://imexam.readthedocs.io
  dev_url: https://github.com/spacetelescope/imexam

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - sosey
