travis:
  secure:
    BINSTAR_TOKEN: PAziGaMlCjuHJcVY+x2QNSq+m/Ffrt5nSItGegHS0HFscMfIWswUlXQAEjA3P0I5P86uHQVxtHYEZC/7k2UymNSarfRxFCHjxWI+nDm1EMMZq3k6KS0lrdxk3D24Z/jPXodc1VoxF0vk6UCUIBnxGi1++qUTcw2/XrxjkRy1qw/O/PYaDDWyGNY1d3xJZVb4Z7n/LE5yvmlDT+bojXBjww8ea004oL3nenOPKcfRHdDQWYl+czfmycSg9Mwu0J0OCa25f6zag3sunijNvtNkZnt7i3JBkMZjdCn7OjHPMk7yYWAKbuuj2AKwiDy18m6/NrI9UkWV9RQCTtT+xMmk1yJej69OWq9GFsfAaVmUz6G1u6slsalRGZgkSXeMI4/EcXIRP0UUEABwY5VR2kXj0Oj/dmxaPCj+URcCJhD6tklxP0W6GFHu1dUyztUF8d614G55BcdXkFnWENvWMP2rbOk7RIqpbJ3h8K7XxZxDF7uw2V409jMf90rlgPGD+gFbdliDLMIAWUM9BWVCIbzHkkcX9rkbH54RBfP6s2D7P737vrOHci/0holCvjrNKtSsYmaauMrHysyS3eCx37CIiNRxXh8vEKFcTc9iWxzz80P3rnvSDezslzLY/PsS7kjKXLaemLt7gH5mazcFDLCjEHVwQAl2UsTUENeFI5sCKoc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
